export const ERROR_STATES = {
  ERROR_SETUP: "ERROR_SETUP",
  ERROR_TRANSFER: "ERROR_TRANSFER",
  ERROR_NETWORK: "ERROR_NETWORK",
  ERROR_RECOVER: "ERROR_RECOVER",
} as const;
export type ErrorStates = keyof typeof ERROR_STATES;

export const SCREEN_STATES = {
  LOADING: "LOADING",
  EXISTING_BALANCE: "EXISTING_BALANCE",
  SWAP: "SWAP",
  RECOVER: "RECOVER",
  RECOVER_SUCCESS: "RECOVER_SUCCESS",
  LISTENER: "LISTENER",
  STATUS: "STATUS",
  SUCCESS: "SUCCESS",
  ...ERROR_STATES,
} as const;
export type ScreenStates = keyof typeof SCREEN_STATES;
